// frontend-angular/src/app/components/navbar/navbar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  constructor(){

  }

}

<div class="flex items-center justify-center w-full bg-primaryBackground navbar-height">
    <div class="flex items-center justify-between navbar-height navbar-width">
        <img src="/assets/resume_icon.svg" class="logo" alt="logo">
        <p class="font-semibold text-primaryForeground">Applify</p>
        <div>
            <button onclick="logout()" class="hover:bg-accent bg-accent text-secondaryForeground pt-2 pb-2 pl-4 pr-4 rounded font-medium">Logout</button>
        </div>
    </div>
</div>

// frontend/src/components/Navbar/Navbar.jsx
import { Button, Flex, Image, Text } from "@chakra-ui/react";
import { useMediaQuery } from "react-responsive";
import { theme } from "../../theme";
import resumeIcon from "../../assets/resume_icon.svg";

function NavBar() {
  const isMobile = useMediaQuery({ query: "(max-width: 1080px)" });

  const logout = () => {
    localStorage.setItem('applifyUser', '');
    window.location.reload();
  }

  return isMobile ? (
    <Flex
      as="nav"
      alignItems="center"
      justify="space-between"
      h="10vh"
      w="100%"
      backgroundColor={theme.primaryBackground}
    >
      <Image src={resumeIcon} h="6vh"></Image>
        <Text fontWeight="semibold" color={theme.primaryForeground}>Applify</Text>
        <Flex mr="8px">
          <Button onClick={logout} _hover={{ backgroundColor: theme.accent }} backgroundColor={theme.accent} color={theme.secondaryForeground}>
            Logout
          </Button>
        </Flex>
    </Flex>
  ) : (
    <Flex alignItems="center" justifyContent="center" as="nav" h="10vh" w="100%" backgroundColor={theme.primaryBackground}>
      <Flex w="1080px" alignItems="center" justifyContent="space-between" h="10vh">
        <Image src={resumeIcon} h="6vh"></Image>
        <Text fontWeight="semibold" color={theme.primaryForeground}>Applify</Text>
        <Flex>
          <Button onClick={logout} _hover={{ backgroundColor: theme.accent }} backgroundColor={theme.accent} color={theme.secondaryForeground}>
            Logout
          </Button>
        </Flex>
      </Flex>
    </Flex>
  );
}

export default NavBar;
